### ISSUE TITLE
'dict' object has no attribute 'shape'

### ISSUE THREAD

**Issue by matrix4767** [v0xie/sd-webui-semantic-guidance#19]
Error executing callback cfg_denoiser_callback for G:\stable-webui\extensions\sd-webui-semantic-guidance\scripts\sega.py
    Traceback (most recent call last):
      File "G:\stable-webui\modules\script_callbacks.py", line 216, in cfg_denoiser_callback
        c.callback(params)
      File "G:\stable-webui\extensions\sd-webui-semantic-guidance\scripts\sega.py", line 181, in <lambda>
        y = lambda params: self.on_cfg_denoiser_callback(params, concept_conds, concepts_sega_params)
      File "G:\stable-webui\extensions\sd-webui-semantic-guidance\scripts\sega.py", line 236, in on_cfg_denoiser_callback
        num_repeats = (tensor.shape[1] - text_uncond.shape[1]) // empty.shape[1]
    AttributeError: 'dict' object has no attribute 'shape'
    
    This issue keeps repeating every 5% of the generation and the output is not affected by this extension at all.

**Comment by sandner-art** [comment]
Same here.

**Comment by v0xie** [comment]
What version of A1111 do you have? SD 1.5 or SDXL?

**Comment by matrix4767** [comment]
> What version of A1111 do you have? SD 1.5 or SDXL?

1.5

**Comment by v0xie** [comment]
Can you try on the latest A1111 dev branch?

**Comment by japtain-cack** [comment]
I tried this on the latest dev branch and am getting the same exact error. For context, this happens on the master branch as well.

Although, I feel like it is working. It doesn't cause a hard exception, and continues processing. I've tried adding positive/negative prompts for increasing attention/detail of specific things, and it does seem to work.


```
*** Error executing callback cfg_denoiser_callback for /home/nsnow/git/stable-diffusion-webui/extensions/sd-webui-semantic-guidance/scripts/sega.py
    Traceback (most recent call last):
      File "/home/nsnow/git/stable-diffusion-webui/modules/script_callbacks.py", line 216, in cfg_denoiser_callback
        c.callback(params)
      File "/home/nsnow/git/stable-diffusion-webui/extensions/sd-webui-semantic-guidance/scripts/sega.py", line 181, in <lambda>
        y = lambda params: self.on_cfg_denoiser_callback(params, concept_conds, concepts_sega_params)
      File "/home/nsnow/git/stable-diffusion-webui/extensions/sd-webui-semantic-guidance/scripts/sega.py", line 236, in on_cfg_denoiser_callback
        num_repeats = (tensor.shape[1] - text_uncond.shape[1]) // empty.shape[1]
    AttributeError: 'dict' object has no attribute 'shape'
```

**Comment by minipuft** [comment]
In the same boat it seems to work, just messes with the parameter values when sending to txt2img, or img2img, and doesn't include anything else but the semantic guidance information.

**Comment by Skifoid** [comment]
It seems that prompts longer than 75 tokens are not supported.

**Comment by ArnorWing** [comment]
> It seems that prompts longer than 75 tokens are not supported.

It didnt work for me with less than 75 tokens.

**Comment by Shurale7** [comment]
The idea of extending the functionality seems interesting, but when it is implemented, this error occurs, which cannot be eliminated.

**Comment by AG-w** [comment]
same issue
it's not working at all
I'll try other extension instead of this broken one

**Comment by AG-w** [comment]
I guess I found the fix?
this part
```python
                        # initialize here because we don't know the shape/dtype of the tensor until we reconstruct it
                        for key, tensor in tensor_dict.items():
                                if tensor.shape[1] != text_uncond[key].shape[1]:
                                        empty = shared.sd_model.cond_stage_model_empty_prompt
                                        num_repeats = (tensor.shape[1] - text_uncond.shape[1]) // empty.shape[1]
                                        if num_repeats < 0:
                                                tensor = pad_cond(tensor, -num_repeats, empty)
```
just add a condition then it will work on SD1.5 
```python
                        # initialize here because we don't know the shape/dtype of the tensor until we reconstruct it
                        for key, tensor in tensor_dict.items():
                                if tensor.shape[1] != text_uncond[key].shape[1]:
                                        empty = shared.sd_model.cond_stage_model_empty_prompt
                                        if key == "crossattn":
                                                num_repeats = (tensor.shape[1] - text_uncond[key].shape[1]) // empty.shape[1]
                                        else:
                                                num_repeats = (tensor.shape[1] - text_uncond.shape[1]) // empty.shape[1]
                                        if num_repeats < 0:
                                                tensor = pad_cond(tensor, -num_repeats, empty)
```

**Comment by xgt1986627** [comment]
but XL still don't work
